[workspace]
resolver = "2"
members = [
  "cli",          # command line definition
  "jucenit",      # binary entrypoint
  "jucenit_core", # requests to nginx API
  "migration",    # generate database
]
