[[unit]]
listeners = ["*:80"]

[unit.match]
uri = "http://example.com/"

[unit.action]
proxy = "http://127.0.0.1:8888"

[[unit]]
listeners = ["*:80"]

[unit.match]
uri = "http://test.com/"

[unit.action]
proxy = "http://127.0.0.1:8333"
