# A merge of config files: example.com and test.com
[[unit]]
listeners = ["*:443", "*:886"]

[unit.match]
hosts = ["example.com", "example2.de"]

[unit.action]
proxy = "http://127.0.0.1:9080"

[[unit]]
listeners = ["*:443"]

[unit.match]
hosts = ["test.com"]

[unit.action]
proxy = "http://127.0.0.1:8333"
