[[unit]]
listeners = ["*:80"]

[unit.match]
host = "example.com"

[unit.action]
proxy = "http://127.0.0.1:9080"

[[unit]]
listeners = ["*:80"]

[unit.match]
host = "test.com"

[unit.action]
proxy = "http://127.0.0.1:8333"
