//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "listener")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub ip_socket: String,
    pub tls: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::match_listener::Entity")]
    MatchListener,
}

impl Related<super::match_listener::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MatchListener.def()
    }
}

impl Related<super::ng_match::Entity> for Entity {
    fn to() -> RelationDef {
        super::match_listener::Relation::NgMatch.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::match_listener::Relation::Listener.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
