//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "action")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub raw_params: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::ng_match::Entity")]
    NgMatch,
}

impl Related<super::ng_match::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::NgMatch.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
