//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "host")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub domain: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::match_host::Entity")]
    MatchHost,
}

impl Related<super::match_host::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MatchHost.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
